# render.yaml
services:
  - type: web
    name: personal-portfolio
    env: node
    buildCommand: "npm install && npx vite build"
    startCommand: "npx vite preview"
    envVars:
      - key: NODE_ENV
        value: production
